### ISSUE TITLE
Are there any plans to upgrade the project to julia 1.5 or higher?

### ISSUE THREAD

**Issue by zzphd** [odow/DynamicProgramming.jl#9]
Many thanks to the developers for the excellent work.  When I read the code I found that the project is based on julia 0.6, which seems a bit outdated. I tried to upgrade it to julia 1.5, but it didn't work because I wasn't very familiar with julia 0.6. So I wonder if the developers have plans to upgrade it to julia 1.5 or higher?

**Comment by odow** [comment]
I have no plans to do so. 

See also: https://github.com/wanqiuchansheng/sddpy/issues/2

**Comment by zzphd** [comment]
Thank you very much for your advice, I have made changes to the repository based on your suggestions.
